### ISSUE TITLE
关于常量设置默认值

### ISSUE THREAD

**Issue by Rupert333** [buyili/api-generator-plus#10]
请问下下图这种常量如何设置默认值，已有设置处不能满足需求（有可能是我的打开姿势不对，敬请指正）
![image](https://github.com/user-attachments/assets/ac2ab845-4daa-4f98-8368-e17c0179daf5)
![image](https://github.com/user-attachments/assets/e90c4494-f0e9-4c23-a947-41cc1f0341ea)

**Comment by buyili** [comment]
应该是这个bug #9  ，v1.0.14版本已修复

**Comment by Rupert333** [comment]
升级1.0.4版本 #9 问题已经修复了，接口中常量已经可以解析为代码中定义的常量，但是如何才能对这个常量设置其他默认值呢？

**Comment by buyili** [comment]
哦哦，这样啊，目前没有这个功能。

**Comment by Rupert333** [comment]
get
