### ISSUE TITLE
大佬，希望能加一个跟fetch类似的生成axios代码的功能！

### ISSUE THREAD

**Issue by PDMoFan** [buyili/api-generator-plus#2]
现在前端越来越多用的axios，所以希望能有一个像现在功能里面一键生成fetch一样的功能，能够一键生成axios.

**Comment by PDMoFan** [comment]
大佬关注一下这个需求啊！前端现在越来越多的项目使用vue，然后都是使用axios代替ajax。axios比原生的的Fetch特性和兼容性更好。所以希望出一个跟生成fetch类似的生成axios代码的功能！！！！！
![image](https://user-images.githubusercontent.com/40638512/120282954-3e1c1e80-c2ed-11eb-8138-2e929891ff99.png)

**Comment by buyili** [comment]
axios虽然用的越来越多，但是一般不都会自己封装一次吗？感觉有点鸡肋啊😂😂

**Comment by PDMoFan** [comment]
大佬，这个功能不会鸡肋啊。目前一些公司都是新项目用的是vue脚手架+axios，这种情况下一般都会再封装一层，这没什么问题。但是更多的是老项目，单纯的引入vue.min.js然后加上axios,或者单纯的使用axios替代ajax这都是很多的，远比vue脚手架+axios这种前后端分离的架构项目多的多啊！

**Comment by buyili** [comment]
v1.0.11版本已上线，包含copy as axios功能✨✨✨
