### ISSUE TITLE
上传错误提示

### ISSUE THREAD

**Issue by CobraStarLE** [buyili/api-generator-plus#8]
<img width="367" alt="image" src="https://github.com/buyili/api-generator-plus/assets/30492390/48d09ed9-f0ce-4c4b-8a74-fcb0b7e2b4ba">
<img width="702" alt="image" src="https://github.com/buyili/api-generator-plus/assets/30492390/a318a8d7-8410-4e6f-b1d6-24014d60a8c1">
您好，我的项目是多模块，但是我上传接口的时候报了默认token为空的提示，您能帮忙看看这是什么原因吗，谢谢！

**Comment by buyili** [comment]
抱歉，昨天才看到问题。此问题已在 [v1.0.14](https://github.com/buyili/api-generator-plus/releases/tag/v1.0.14) 版本修复。感谢您的反馈🙏
