### ISSUE TITLE
插件不能解析配置在类上的RequestMapping 路径

### ISSUE THREAD

**Issue by Rupert333** [buyili/api-generator-plus#9]
在方法上，通过curl (bash)方式升成接口地址时，接口地址中只包含了方法上的接口路径，没有包含类上的接口路径

**Comment by buyili** [comment]
感谢反馈🙏
![image](https://github.com/user-attachments/assets/0f161c0d-6a21-4c68-832c-9489678b9286)
![image](https://github.com/user-attachments/assets/fd792b0b-9891-462b-b3e6-6206e433fa74)
可以包含类上的路径，类上接口路径其他写法也可以，如下图

![image](https://github.com/user-attachments/assets/215604ee-89e5-4b9b-8fb7-199214e346a1)
![image](https://github.com/user-attachments/assets/1bfe4530-adb2-420a-b35e-20344d4027fc)

![image](https://github.com/user-attachments/assets/10c22916-ca63-4454-ad9a-d3d4ca24133c)
![image](https://github.com/user-attachments/assets/4fc9419d-ed6c-4216-8546-52c7c8a83a81)

如果类上的路径还有其他写法，或者还是不行的话，麻烦贴一下相关代码。

**Comment by Rupert333** [comment]
<img width="943" alt="image" src="https://github.com/user-attachments/assets/fa4d49cc-a78e-460c-b845-e998d72065d4">
这种方式确实是可以复制所有路径，下面这种情况是无法解析的
<img width="648" alt="image" src="https://github.com/user-attachments/assets/06079dd5-583f-429f-a5fa-fc0cb0580d39">
<img width="449" alt="image" src="https://github.com/user-attachments/assets/29f041d8-b9c2-4a0a-890c-1b1c48710a59">

**Comment by buyili** [comment]
此问题已在 [v1.0.14](https://github.com/buyili/api-generator-plus/releases/tag/v1.0.14) 版本修复。感谢您的反馈🙏
